codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "10...100"
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: 10
        threshold: 3%
        base: auto 

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "src/light-godwoken/godwoken-v1"  # ignore folders and all its contents
  - "src/light-godwoken/omni-lock"
  - "src/light-godwoken/schemas/generated"