export const CKB_USDC_ISSUER_PRIVATE_KEY = process.env.REACT_APP_CKB_USDC_ISSUER_PRIVATE_KEY!;
export const CKB_SUDT_SCRIPT_CODE_HASH = process.env.REACT_APP_CKB_SUDT_SCRIPT_CODE_HASH!;

export const GODWOKEN_V1_CHAIN_NAME = process.env.REACT_APP_GODWOKEN_V1_CHAIN_NAME!;
export const GODWOKEN_V1_NATIVE_CURRENCY_NAME = process.env.REACT_APP_GODWOKEN_V1_NATIVE_CURRENCY_NAME!;
export const GODWOKEN_V1_NATIVE_CURRENCY_SYMBOL = process.env.REACT_APP_GODWOKEN_V1_NATIVE_CURRENCY_SYMBOL!;
export const GODWOKEN_V1_NATIVE_CURRENCY_DECIMALS = process.env.REACT_APP_GODWOKEN_V1_NATIVE_CURRENCY_DECIMALS!;
export const GODWOKEN_V1_RPC_URL = process.env.REACT_APP_GODWOKEN_V1_RPC_URL!;
export const GODWOKEN_V1_BLOCK_EXPLORER_URL = process.env.REACT_APP_GODWOKEN_V1_BLOCK_EXPLORER_URL!;
export const CKB_EXPLORER_URL = process.env.REACT_APP_CKB_EXPLORER_URL!;
